print ("------------------------------------")
print ("Tugas 1 sisop kelas B")
print ("------------------------------------")
print ("Nama: Fadhilah Nur Hidayat")
print ("NPM : 21083010082")
print ("------------------------------------")
print ("sangat asik sekali")
print ("------------------------------------")
print ("Halo dunia!")
print ("Ini adalah skrip Bash pertamaku di linux")
